# Generated by Django 3.1.3 on 2020-12-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user', max_length=10, unique=True)),
                ('user_password', models.CharField(db_column='password', max_length=50)),
                ('user_vertify_code', models.IntegerField(blank=True, db_column='vcode', null=True)),
                ('token', models.CharField(blank=True, db_column='token', max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LoginInfo',
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.ImageField(default='images/default.png', upload_to='images')),
                ('email_num', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('gender', models.NullBooleanField()),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_num', models.CharField(blank=True, db_column='phone', max_length=11, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booksapp.logininfo')),
            ],
            options={
                'db_table': 'AccountInfo',
            },
        ),
    ]
