# Generated by Django 3.1.3 on 2020-12-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=32, unique=True)),
                ('bpub_data', models.DateField(null=True)),
                ('bauthor', models.CharField(max_length=255, null=True)),
                ('bcontent', models.CharField(blank=True, max_length=3000, null=True)),
                ('bcomment', models.CharField(blank=True, max_length=500, null=True)),
                ('bscore', models.FloatField(blank=True, default=0, null=True)),
                ('bnum', models.IntegerField(default=5)),
                ('can_borrow', models.IntegerField(default=5)),
                ('borrowed', models.IntegerField(default=0)),
            ],
        ),
    ]
