# Generated by Django 3.1.3 on 2020-12-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0003_booksimgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('have_borrow', models.IntegerField(default=0)),
                ('books', models.ManyToManyField(blank=True, null=True, to='booksapp.BooksInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booksapp.logininfo')),
            ],
        ),
    ]
