# Generated by Django 3.1.3 on 2020-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_borrowinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinfo',
            name='books',
            field=models.ManyToManyField(blank=True, to='booksapp.BooksInfo'),
        ),
    ]
